version: '3'
services:
  web:
    build: .
    command: bundle exec rails s -p 3001 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3001:3001"
    environment:
       - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
  redis:
    image: redis
